//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMap : DbContext
    {
        public EntitiesMap()
            : base("name=EntitiesMap")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLOG> TBLOGs { get; set; }
        public virtual DbSet<TBLOCATIONSTATU> TBLOCATIONSTATUS { get; set; }
        public virtual DbSet<TBPICTUREFORLOCATION> TBPICTUREFORLOCATIONs { get; set; }
        public virtual DbSet<TBLLOCATION> TBLLOCATIONs { get; set; }
        public virtual DbSet<TBLOCATIONUPDATING> TBLOCATIONUPDATINGs { get; set; }
        public virtual DbSet<TBLOCATIONTEMP> TBLOCATIONTEMPs { get; set; }
    }
}
