//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesLBCosting : DbContext
    {
        public EntitiesLBCosting()
            : base("name=EntitiesLBCosting")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_FARMER_GETLIST> V_FARMER_GETLIST { get; set; }
        public virtual DbSet<V_LOCATION_GETLIST> V_LOCATION_GETLIST { get; set; }
    }
}
