//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MTGROUPBYUSER> MTGROUPBYUSERs { get; set; }
        public virtual DbSet<MTGROUPUSER> MTGROUPUSERs { get; set; }
        public virtual DbSet<MTLOG> MTLOGs { get; set; }
        public virtual DbSet<MTUSER> MTUSERs { get; set; }
        public virtual DbSet<MTUSERBYMENU> MTUSERBYMENUs { get; set; }
        public virtual DbSet<MTUSERBYGROUPMENU> MTUSERBYGROUPMENUs { get; set; }
        public virtual DbSet<MTAPPBYUSER> MTAPPBYUSERs { get; set; }
        public virtual DbSet<MTUSERBYSUBUSER> MTUSERBYSUBUSERs { get; set; }
        public virtual DbSet<MTUSERBYSUBMENU> MTUSERBYSUBMENUs { get; set; }
        public virtual DbSet<MTGROUPBYMENU> MTGROUPBYMENUs { get; set; }
        public virtual DbSet<MTGROUPMENUBYSUBMENU> MTGROUPMENUBYSUBMENUs { get; set; }
        public virtual DbSet<MTUSERBYGROUPUSER> MTUSERBYGROUPUSERs { get; set; }
        public virtual DbSet<MTMENU> MTMENUs { get; set; }
        public virtual DbSet<MTGROUPMENU> MTGROUPMENUs { get; set; }
        public virtual DbSet<MTSUBMENU> MTSUBMENUs { get; set; }
        public virtual DbSet<MTAPPLICATION> MTAPPLICATIONs { get; set; }
        public virtual DbSet<JAPPLICATION> JAPPLICATIONs { get; set; }
    }
}
