//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOCATIONUPDATING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOCATIONUPDATING()
        {
            this.TBLLOCATIONs = new HashSet<TBLLOCATION>();
        }
    
        public string MLOCATION { get; set; }
        public Nullable<decimal> MLAT { get; set; }
        public Nullable<decimal> MLONG { get; set; }
        public string MDIVISION { get; set; }
        public string MREGION { get; set; }
        public string MCONTACT { get; set; }
        public string MNUMBERPHONE { get; set; }
        public string MADDRESS { get; set; }
        public string MSUBDIVISION { get; set; }
        public string IDLOCATIONLINK { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public decimal ID { get; set; }
        public string UPDATEEMAIL { get; set; }
        public string NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLOCATION> TBLLOCATIONs { get; set; }
    }
}
