//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOG
    {
        public decimal LOGID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string TABLE_NAME { get; set; }
        public string KEY_NAME { get; set; }
        public string KEY_VALUE { get; set; }
        public string TYPE { get; set; }
        public string CONTENT { get; set; }
        public string EMAIL { get; set; }
    }
}
