//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOCATIONTEMP
    {
        public decimal IDLOCATION { get; set; }
        public string MLOCATION { get; set; }
        public Nullable<decimal> MLAT { get; set; }
        public Nullable<decimal> MLONG { get; set; }
        public string MDIVISION { get; set; }
        public string MREGION { get; set; }
        public string MCONTACT { get; set; }
        public string MNUMBERPHONE { get; set; }
        public string MADDRESS { get; set; }
        public string MSUBDIVISION { get; set; }
        public string IDLOCATIONLINK { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEEMAIL { get; set; }
        public Nullable<decimal> LOCATIONSTATUS { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> IDLOCATIONUPDATE { get; set; }
        public Nullable<decimal> ESIGNINGID { get; set; }
    }
}
