//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPICTUREFORLOCATION
    {
        public decimal ID { get; set; }
        public string PICTURENAME { get; set; }
        public Nullable<decimal> TBLOCATIONID { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    
        public virtual TBLLOCATION TBLLOCATION { get; set; }
    }
}
