//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FARMER_GETLIST
    {
        public string FARMERCODE { get; set; }
        public string FARMERNAMER { get; set; }
        public string NLOCK { get; set; }
        public string NACTIVE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public string FADDRESS { get; set; }
        public Nullable<decimal> FLOORSPACE { get; set; }
        public Nullable<decimal> HENHOUSEQTY { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> AREAID { get; set; }
        public string FARMOWNERID { get; set; }
        public string STATUSCHICHIN { get; set; }
        public string WAREHOUSEID { get; set; }
        public string QUARANTINE { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public string REGIONID { get; set; }
        public string NOTES { get; set; }
        public string SUBAREAID { get; set; }
        public string UNITID { get; set; }
        public string FARMOWNERNAME { get; set; }
        public string AREANAME { get; set; }
    }
}
