//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LOCATION_GETLIST
    {
        public string LOCATIONID { get; set; }
        public string LOCATIONNAME { get; set; }
        public string REGION { get; set; }
        public string DIVISION { get; set; }
        public string UNIT { get; set; }
        public string CONTACTNAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string ADDRESS { get; set; }
        public string PROVINCENAME { get; set; }
        public string BIRDTYPE { get; set; }
    }
}
